name: cluster-sql

services:
  postgres:
    image: postgres:17-trixie
    #user: "${UID}:${GID}" # Se habilita en linux
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${POSTGRES_TZ}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pdAdmin4:
    image: dpage/pgadmin4
    #user: "${UID}:${GID}" # Se habilita en linux
    container_name: pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json

  mariadb:
    image: mariadb:lts-ubi9
    #user: "${UID}:${GID}" # Se habilita en linux
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      TZ: ${MARIADB_TZ}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    #restart: unless-stopped

  phpmyadmin:
    image: arm64v8/phpmyadmin:latest # Para MacOS
    #image: phpmyadmin # Para Windows o Linux
    #user: "${UID}:${GID}" # Se habilita en linux
    restart: always
    ports:
      - "${PMA_PORT}:80" # Access phpMyAdmin via http://localhost:8082
    environment:
      PMA_HOST: ${PMA_HOST} # Tells phpMyAdmin to connect to the 'db' service (container name)
      MYSQL_ROOT_PASSWORD: ${PMA_ROOT_PASSWORD} # Use the same root password as the 'db' service
      PMA_ARBITRARY: 1 # Allows connecting to other hosts via the login page if needed
      TZ: ${PMA_TZ}
    depends_on:
      - mariadb # Ensures the 'db' container starts first

#volumes:
#  mariadb_data:
#    driver: local
